In [14]:
import numpy as np
vek = np.arange(1,11)
print(f'вектор з першими 10 натуральними числами - {vek}')
m = np.zeros((3,3), dtype=int)
print(f'Матриця ролзміром 3х3 , що складається з нулів - {m}')
mrx = np.random.randint(1,11, size=(5, 5))
print(f'Матриця розміром 5х5 з випадковими числами від 1 до 10  - {mrx}')
mtrx = np.random.randint(0,2, size=(4, 4))
print(f'Матриця розміром 4х4 з випадковим 0-1 - {mtrx}')
array1 = np.random.randint(1,11, size=(5))
array2 = np.random.randint(1,11, size=(5))

plus = array1 + array2 
minus = array1 - array2
multi = array1 * array2

print(f'Вектори - {array1} , {array2} Результат додавання - {plus}, результат віднімання - {minus} , результат множення {multi}')
ary1 = np.random.random(size=(7))
ary2 = np.random.random(size=(7))

mul = np.dot(ary1 , ary2) 
print(f'Скалярний добуток векторів {ary1} , i {ary2} - {mul}')
mrx1 = np.random.random(size=(2,2))
mrx2 = np.random.random(size=(2,3))

multiply = np.dot(mrx1,mrx2)
print(f'Результат множення матриць {mrx1} , i {mrx2} - {multiply}')

matrix = np.random.randint(1,11, size=(3,3))

matrix_inv = np.linalg.inv(matrix)
print(f'Обернена матриця до {matrix} - {matrix_inv}')
bef = np.random.randint(1,11, size=(4,4))

transp = bef.T
print(f'транспортована матриця до {bef} - {transp}')


вектор з першими 10 натуральними числами - [ 1  2  3  4  5  6  7  8  9 10]
Матриця ролзміром 3х3 , що складається з нулів - [[0 0 0]
 [0 0 0]
 [0 0 0]]
Матриця розміром 5х5 з випадковими числами від 1 до 10  - [[ 9  8  5  3  1]
 [ 3 10  3  7  6]
 [ 5  5  9  7  2]
 [ 2  4  2  1 10]
 [ 8  3  4  8  8]]
Матриця розміром 4х4 з випадковим 0-1 - [[1 0 1 1]
 [0 1 1 0]
 [0 1 1 0]
 [0 1 0 1]]
Вектори - [5 2 5 3 1] , [9 2 7 6 8] Результат додавання - [14  4 12  9  9], результат віднімання - [-4  0 -2 -3 -7] , результат множення [45  4 35 18  8]
Скалярний добуток векторів [0.38360761 0.23030987 0.68358525 0.45293936 0.84271221 0.9915021
 0.85446348] , i [0.99851566 0.24001608 0.3387018  0.03070179 0.96705376 0.15792228
 0.11310638] - 1.75192744315822
Результат множення матриць [[0.36568055 0.1182086 ]
 [0.64589301 0.18010691]] , i [[0.73136807 0.1083948  0.61207778]
 [0.54173407 0.55655827 0.29784684]] - [[0.3314847  0.10542784 0.25903299]
 [0.56995557 0.17025144 0.44898104]]
Обернена матриця до [