In [35]:
import numpy as np
vek = np.arange(1,11)
print(f'вектор з першими 10 натуральними числами - {vek}')
m = np.zeros((3,3), dtype=int)
print(f'Матриця ролзміром 3х3 , що складається з нулів - {m}')
mrx = np.random.randint(1,11, size=(5, 5))
print(f'Матриця розміром 5х5 з випадковими числами від 1 до 10  - {mrx}')
mtrx = np.random.randint(0,2, size=(4, 4))
print(f'Матриця розміром 4х4 з випадковим 0-1 - {mtrx}')
array1 = np.random.randint(1,11, size=(5))
array2 = np.random.randint(1,11, size=(5))

plus = array1 + array2 
minus = array1 - array2
multi = array1 * array2

print(f'Вектори - {array1} , {array2} Результат додавання - {plus}, результат віднімання - {minus} , результат множення {multi}')
ary1 = np.random.random(size=(7))
ary2 = np.random.random(size=(7))

mul = np.dot(ary1 , ary2) 
print(f'Скалярний добуток векторів {ary1} , i {ary2} - {mul}')
mrx1 = np.random.random(size=(2,2))
mrx2 = np.random.random(size=(2,3))

multiply = np.dot(mrx1,mrx2)
print(f'Результат множення матриць {mrx1} , i {mrx2} - {multiply}')

matrix = np.random.randint(1,11, size=(3,3))

matrix_inv = np.linalg.inv(matrix)
print(f'Обернена матриця до {matrix} - {matrix_inv}')
bef = np.random.randint(1,11, size=(4,4))

transp = bef.T
print(f'транспортована матриця до {bef} - {transp}')

mrx = np.random.randint(1,11 , size=(3,4))
vek = np.random.randint(1,11 , size=(4))

multiply = np.dot(mrx,vek)

print(f'Множення матриці - {mrx} на вектор {vek} - {multiply}')

mrx = np.random.randint(0,2 , size=(2,3))
vek = np.random.randint(0,2 , size=(3))

multiply = np.dot(mrx,vek)

print(f'Множення матриці - {mrx} на вектор {vek} - {multiply}')

mrx1 = np.random.randint(1,11, size=(2,2))
mrx2 = np.random.randint(1,11, size=(2,2))

multiply = mrx1*mrx2
print(f'Поелементарне множеня матриць {mrx1}, i {mrx2} - {multiply}')

mrx1 = np.random.randint(1,11, size=(2,2))
mrx2 = np.random.randint(1,11, size=(2,2))

multiply = np.dot(mrx1,mrx2)
print(f'добуток матриць {mrx1}, i {mrx2} - {multiply}')

matrix = np.random.randint(1,101 , size=(5,5))

sum = np.sum(matrix)
print(f'Сума всіх елементів матриці {matrix} - {sum}')

mrx1 = np.random.randint(1,11 , size=(4,4))
mrx2 = np.random.randint(1,11 , size=(4,4))

minus = mrx1-mrx2

print(f'Різниця матриць {mrx1}, i {mrx2} - {minus}')

matrix = np.random.random((3, 3))


row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)

print("Матриця:")
print(matrix)
print("Вектор-стовпець з сумами рядків:")
print(column_vector)


matrix = np.random.randint(0,101 , size=(3,4))
new_matrix = np.square(matrix)

print(f'Матриця - {matrix}. Матриця з квадратними елементами минулої - {new_matrix}')

vektor = np.random.randint(1,51,size=(4))

new_vektor = np.sqrt(vektor)

print(f'Вектор - {vektor} , вектор з елементами минулого під арефметичним коренем - {new_vektor}')

вектор з першими 10 натуральними числами - [ 1  2  3  4  5  6  7  8  9 10]
Матриця ролзміром 3х3 , що складається з нулів - [[0 0 0]
 [0 0 0]
 [0 0 0]]
Матриця розміром 5х5 з випадковими числами від 1 до 10  - [[ 6  7  3  7 10]
 [ 9  5  1  9  3]
 [ 2  8  6  5  4]
 [ 4  1  6  2  1]
 [ 4  5  7  1  5]]
Матриця розміром 4х4 з випадковим 0-1 - [[0 0 0 1]
 [0 1 1 1]
 [0 0 0 1]
 [1 1 0 0]]
Вектори - [9 5 2 1 3] , [9 5 3 7 3] Результат додавання - [18 10  5  8  6], результат віднімання - [ 0  0 -1 -6  0] , результат множення [81 25  6  7  9]
Скалярний добуток векторів [0.59845141 0.35792075 0.72090752 0.53842248 0.22886167 0.77474919
 0.67967704] , i [9.98132657e-01 2.86654650e-01 6.48423820e-01 4.27022716e-01
 8.08434543e-01 5.59682880e-04 9.84563920e-01] - 2.251944567900569
Результат множення матриць [[0.94280053 0.9862057 ]
 [0.87317507 0.84340626]] , i [[0.99542887 0.3775365  0.33646157]
 [0.51982407 0.91698385 0.79692949]] - [[1.45114432 1.26027632 1.10315255]
 [1.30760654 1.10304538 0.96