In [20]:
import numpy as np
vek = np.arange(1,11)
print(f'вектор з першими 10 натуральними числами - {vek}')
m = np.zeros((3,3), dtype=int)
print(f'Матриця ролзміром 3х3 , що складається з нулів - {m}')
mrx = np.random.randint(1,11, size=(5, 5))
print(f'Матриця розміром 5х5 з випадковими числами від 1 до 10  - {mrx}')
mtrx = np.random.randint(0,2, size=(4, 4))
print(f'Матриця розміром 4х4 з випадковим 0-1 - {mtrx}')
array1 = np.random.randint(1,11, size=(5))
array2 = np.random.randint(1,11, size=(5))

plus = array1 + array2 
minus = array1 - array2
multi = array1 * array2

print(f'Вектори - {array1} , {array2} Результат додавання - {plus}, результат віднімання - {minus} , результат множення {multi}')
ary1 = np.random.random(size=(7))
ary2 = np.random.random(size=(7))

mul = np.dot(ary1 , ary2) 
print(f'Скалярний добуток векторів {ary1} , i {ary2} - {mul}')
mrx1 = np.random.random(size=(2,2))
mrx2 = np.random.random(size=(2,3))

multiply = np.dot(mrx1,mrx2)
print(f'Результат множення матриць {mrx1} , i {mrx2} - {multiply}')

matrix = np.random.randint(1,11, size=(3,3))

matrix_inv = np.linalg.inv(matrix)
print(f'Обернена матриця до {matrix} - {matrix_inv}')
bef = np.random.randint(1,11, size=(4,4))

transp = bef.T
print(f'транспортована матриця до {bef} - {transp}')

mrx = np.random.randint(1,11 , size=(3,4))
vek = np.random.randint(1,11 , size=(4))

multiply = np.dot(mrx,vek)

print(f'Множення матриці - {mrx} на вектор {vek} - {multiply}')

mrx = np.random.randint(0,2 , size=(2,3))
vek = np.random.randint(0,2 , size=(3))

multiply = np.dot(mrx,vek)

print(f'Множення матриці - {mrx} на вектор {vek} - {multiply}')

mrx1 = np.random.randint(1,11, size=(2,2))
mrx2 = np.random.randint(1,11, size=(2,2))

multiply = mrx1*mrx2
print(f'Поелементарне множеня матриць {mrx1}, i {mrx2} - {multiply}')

mrx1 = np.random.randint(1,11, size=(2,2))
mrx2 = np.random.randint(1,11, size=(2,2))

multiply = np.dot(mrx1,mrx2)
print(f'добуток матриць {mrx1}, i {mrx2} - {multiply}')



вектор з першими 10 натуральними числами - [ 1  2  3  4  5  6  7  8  9 10]
Матриця ролзміром 3х3 , що складається з нулів - [[0 0 0]
 [0 0 0]
 [0 0 0]]
Матриця розміром 5х5 з випадковими числами від 1 до 10  - [[ 7  6  2  6  2]
 [ 1  5 10  1  2]
 [ 2  7  4  8  7]
 [10 10  4  2  7]
 [ 7  9  7  2 10]]
Матриця розміром 4х4 з випадковим 0-1 - [[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 1 1]]
Вектори - [8 5 9 6 1] , [7 6 3 8 3] Результат додавання - [15 11 12 14  4], результат віднімання - [ 1 -1  6 -2 -2] , результат множення [56 30 27 48  3]
Скалярний добуток векторів [0.22267156 0.34136485 0.48914874 0.02212867 0.08899358 0.42227475
 0.87750592] , i [0.92446278 0.56649647 0.14016812 0.49800827 0.04748816 0.11728934
 0.97917998] - 1.3918075761130086
Результат множення матриць [[0.35016923 0.37220205]
 [0.39991716 0.09722744]] , i [[0.07040353 0.36330866 0.95575797]
 [0.04064081 0.24687456 0.84056109]] - [[0.03977974 0.21910673 0.64753559]
 [0.03210698 0.16929635 0.46394962]]
Обернена матриця д